import { prisma } from './prisma.js';
import { calculateReadinessScore } from './readinessScore.js';

/**
 * Platform reports (master spec §43).
 *
 * Structured, printable HTML. Every report states its data sources and carries a
 * no-guarantee disclosure. These are NOT consumer credit reports or credit
 * scores and are not an underwriting or funding decision.
 */

export type ReportKind = 'READINESS_REPORT' | 'CREDIT_PROFILE_SUMMARY';

export const REPORT_TITLES: Record<ReportKind, string> = {
  READINESS_REPORT: 'CredX Readiness Report',
  CREDIT_PROFILE_SUMMARY: 'Credit Profile Summary'
};

const DISCLOSURE =
  'This document is generated by CredX from the information listed under "Data sources" below. It is not a consumer credit report, a credit score, a loan or funding decision, or a guarantee of any outcome. Lenders, bureaus, and furnishers apply their own criteria. Figures are estimates and may differ from bureau data.';

export function isReportKind(v: unknown): v is ReportKind {
  return v === 'READINESS_REPORT' || v === 'CREDIT_PROFILE_SUMMARY';
}

function esc(v: unknown): string {
  return String(v ?? '').replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' } as Record<string, string>
  )[c]);
}

function rec(v: unknown): Record<string, unknown> {
  return v && typeof v === 'object' && !Array.isArray(v) ? (v as Record<string, unknown>) : {};
}
function num(v: unknown): number | null {
  if (typeof v === 'number' && Number.isFinite(v)) return v;
  if (typeof v === 'string' && v.trim()) { const n = Number(v.replace(/[$,%]/g, '')); return Number.isFinite(n) ? n : null; }
  if (v && typeof v === 'object' && 'toNumber' in v && typeof (v as any).toNumber === 'function') { const n = (v as any).toNumber(); return Number.isFinite(n) ? n : null; }
  return null;
}

function shell(title: string, clientName: string, bodyHtml: string, dataSources: string[]): string {
  const generated = new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' });
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>${esc(title)}</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #1a2432; max-width: 780px; margin: 32px auto; padding: 0 24px; line-height: 1.5; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  h2 { font-size: 16px; margin: 28px 0 8px; border-bottom: 1px solid #dde3ea; padding-bottom: 4px; }
  .meta { color: #5a6b7d; font-size: 13px; }
  .disclosure { border: 1px solid #e5c76b; background: #fdf6e3; padding: 12px 14px; border-radius: 8px; font-size: 12.5px; margin: 16px 0; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; margin: 8px 0; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #eef1f4; }
  th { color: #5a6b7d; font-weight: 600; }
  ul { padding-left: 20px; }
  .pill { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 700; background: #eef4ff; color: #2b5bd7; }
  .sources { font-size: 12px; color: #5a6b7d; }
  @media print { body { margin: 0; } }
</style></head><body>
<h1>${esc(title)}</h1>
<p class="meta">Prepared for ${esc(clientName)} &middot; Generated ${esc(generated)}</p>
<div class="disclosure">${esc(DISCLOSURE)}</div>
${bodyHtml}
<h2>Data sources</h2>
<ul class="sources">${dataSources.map((s) => `<li>${esc(s)}</li>`).join('')}</ul>
</body></html>`;
}

interface BuiltReport {
  html: string;
  data: Record<string, unknown>;
  disclosure: string;
  dataSources: string[];
  title: string;
}

async function loadClientForReport(clientId: string) {
  return prisma.client.findUnique({
    where: { id: clientId },
    include: {
      user: true,
      progress: true,
      tasks: true,
      creditReports: { include: { tradelines: true }, orderBy: { pulledAt: 'desc' } },
      readinessSnapshots: { orderBy: { createdAt: 'desc' }, take: 12 },
      checkIns: { orderBy: { submittedAt: 'desc' }, take: 4 }
    }
  });
}

function clientName(client: any): string {
  return `${client.user?.firstName ?? ''} ${client.user?.lastName ?? ''}`.trim() || 'CredX member';
}

function commonSources(client: any): string[] {
  const s: string[] = [];
  if (client.creditReports?.length) {
    const latest = client.creditReports[0];
    s.push(`Uploaded credit report data (${client.creditReports.length} on file; most recent ${new Date(latest.pulledAt).toLocaleDateString()})`);
  }
  if (client.progress?.analysis) s.push('CredX credit analysis of the uploaded report(s)');
  const scores = rec(client.progress?.scores);
  if (num(scores.experian) || num(scores.equifax) || num(scores.transunion)) s.push('Self-reported bureau score values');
  if (client.checkIns?.length) s.push(`Weekly check-ins (${client.checkIns.length} recent, most recent ${new Date(client.checkIns[0].submittedAt).toLocaleDateString()})`);
  if (client.currentAddressLine1) s.push('Profile details you provided to CredX');
  if (!s.length) s.push('Your CredX profile only — no credit report has been uploaded yet');
  return s;
}

export async function buildReadinessReport(clientId: string): Promise<BuiltReport> {
  const client = await loadClientForReport(clientId);
  if (!client) throw new Error('Client not found');
  const r = calculateReadinessScore(client);
  const history = (client.readinessSnapshots ?? []).slice().reverse();

  const catRows = r.categories
    .map((c) => `<tr><td>${esc(c.label)}</td><td>${c.score}/${c.maxScore}</td><td>${esc(c.explanation)}</td></tr>`)
    .join('');
  const actionRows = r.nextBestActionDetails
    .map((a) => `<tr><td><span class="pill">${esc(a.priority)}</span></td><td>${esc(a.title)}</td><td>up to +${a.potentialPoints} pts</td></tr>`)
    .join('');
  const histRows = history
    .map((h) => `<tr><td>${new Date(h.createdAt).toLocaleDateString()}</td><td>${h.score}/100</td><td>${esc(h.label)}</td></tr>`)
    .join('');

  const body = `
<h2>Overall</h2>
<p><strong>${r.score}/100 &middot; ${esc(r.label)}</strong> (data quality: ${esc(r.dataQuality)})</p>
<p>${esc(r.disclosure)}</p>
<h2>Category breakdown</h2>
<table><tr><th>Category</th><th>Score</th><th>Notes</th></tr>${catRows}</table>
<h2>Recommended next steps</h2>
<table><tr><th>Priority</th><th>Action</th><th>Potential impact</th></tr>${actionRows}</table>
${histRows ? `<h2>Score history</h2><table><tr><th>Date</th><th>Score</th><th>Label</th></tr>${histRows}</table>` : ''}
<h2>Strengths</h2><ul>${r.strengths.map((s) => `<li>${esc(s)}</li>`).join('')}</ul>
<h2>Opportunities</h2><ul>${r.opportunities.map((s) => `<li>${esc(s)}</li>`).join('')}</ul>`;

  const dataSources = commonSources(client);
  return {
    title: REPORT_TITLES.READINESS_REPORT,
    html: shell(REPORT_TITLES.READINESS_REPORT, clientName(client), body, dataSources),
    data: { score: r.score, label: r.label, dataQuality: r.dataQuality, categories: r.categories, nextBestActionDetails: r.nextBestActionDetails },
    disclosure: DISCLOSURE,
    dataSources
  };
}

export async function buildCreditProfileSummary(clientId: string): Promise<BuiltReport> {
  const client = await loadClientForReport(clientId);
  if (!client) throw new Error('Client not found');

  const tradelines = (client.creditReports ?? []).flatMap((rp: any) => rp.tradelines ?? []);
  const negative = tradelines.filter((t: any) => t.isNegative || /collection|charge.?off|late|past due/i.test(`${t.status} ${t.accountType}`));
  const revolving = tradelines.filter((t: any) => /card|revolving|credit line/i.test(String(t.accountType || '')));
  const analysis = rec(client.progress?.analysis);
  const tiles = rec(analysis.summaryTiles);
  let util = num(tiles.utilization) ?? num(analysis.utilization) ?? num(analysis.averageUtilization);
  if (util != null && util > 1) util = util / 100;
  const scores = rec(client.progress?.scores);
  const bureauScores = [
    ['Experian', num(scores.experian) ?? client.creditReports.find((r: any) => r.bureau === 'EXPERIAN')?.score ?? null],
    ['Equifax', num(scores.equifax) ?? client.creditReports.find((r: any) => r.bureau === 'EQUIFAX')?.score ?? null],
    ['TransUnion', num(scores.transunion) ?? client.creditReports.find((r: any) => r.bureau === 'TRANSUNION')?.score ?? null]
  ];

  const tlRows = tradelines.slice(0, 40)
    .map((t: any) => `<tr><td>${esc(t.creditorName)}</td><td>${esc(t.accountType || '')}</td><td>${esc(t.status || '')}</td><td>${t.balance != null ? `$${Number(t.balance)}` : ''}</td><td>${t.isNegative ? 'Yes' : ''}</td></tr>`)
    .join('');

  const body = `
<h2>Snapshot</h2>
<table>
<tr><th>Accounts on file</th><td>${tradelines.length}</td></tr>
<tr><th>Revolving accounts</th><td>${revolving.length}</td></tr>
<tr><th>Accounts with negative indicators</th><td>${negative.length}</td></tr>
<tr><th>Estimated revolving utilization</th><td>${util != null ? `${Math.round(util * 100)}%` : 'Not available'}</td></tr>
</table>
<h2>Reported score values</h2>
<table><tr><th>Bureau</th><th>Value</th></tr>${bureauScores.map(([b, v]) => `<tr><td>${esc(b)}</td><td>${v != null ? esc(v) : 'Not on file'}</td></tr>`).join('')}</table>
<p class="meta">Score values shown are whatever is on file in CredX (from an uploaded report or self-reported). They are not a live bureau pull.</p>
${tlRows ? `<h2>Tradelines</h2><table><tr><th>Creditor</th><th>Type</th><th>Status</th><th>Balance</th><th>Negative</th></tr>${tlRows}</table>` : '<h2>Tradelines</h2><p>No credit report has been uploaded yet, so there are no tradelines to summarize.</p>'}
<h2>Notes</h2>
<ul>
<li>Negative indicators should be reviewed for accuracy, completeness, and age. CredX does not promise removal of any item.</li>
<li>This summary reflects data as of the sources listed below and may not match a current bureau report.</li>
</ul>`;

  const dataSources = commonSources(client);
  return {
    title: REPORT_TITLES.CREDIT_PROFILE_SUMMARY,
    html: shell(REPORT_TITLES.CREDIT_PROFILE_SUMMARY, clientName(client), body, dataSources),
    data: {
      accounts: tradelines.length, revolving: revolving.length, negative: negative.length,
      utilization: util, bureauScores: Object.fromEntries(bureauScores)
    },
    disclosure: DISCLOSURE,
    dataSources
  };
}

export async function generatePlatformReport(reportId: string): Promise<{ ok: boolean; status: string }> {
  const report = await prisma.platformReport.findUnique({ where: { id: reportId } });
  if (!report) return { ok: false, status: 'missing' };
  if (report.status === 'READY') return { ok: true, status: 'READY' };

  await prisma.platformReport.update({ where: { id: reportId }, data: { status: 'GENERATING' } });
  try {
    const built = report.kind === 'CREDIT_PROFILE_SUMMARY'
      ? await buildCreditProfileSummary(report.clientId)
      : await buildReadinessReport(report.clientId);

    await prisma.platformReport.update({
      where: { id: reportId },
      data: {
        status: 'READY',
        title: built.title,
        html: built.html,
        data: built.data as any,
        disclosure: built.disclosure,
        dataSources: built.dataSources as any,
        generatedAt: new Date(),
        error: null
      }
    });

    const { notifyReportReady } = await import('./notifications.js');
    notifyReportReady(report.clientId, { id: reportId, kind: report.kind, title: built.title });
    return { ok: true, status: 'READY' };
  } catch (err) {
    await prisma.platformReport.update({
      where: { id: reportId },
      data: { status: 'FAILED', error: (err as Error).message.slice(0, 500) }
    });
    return { ok: false, status: 'FAILED' };
  }
}
