redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/ubuntu/.openclaw/workspace/credx-platform/apps/web/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/ubuntu/.openclaw/workspace/credx-platform/apps/web"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/portal"
to = "/portal.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/portal/*"
to = "/portal.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/adminportal"
to = "/adminportal.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/adminportal/*"
to = "/adminportal.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]